version: '3'

services:

  php:
    env_file:
      - .env.prod.local
      - .env.prod
    environment:
      APP_ENV: prod
      SYMFONY_ENV: prod
      PHP_INI_MEMORY_LIMIT: 512M
      TEMPLATE_PHP_INI: production
    networks:
      - default
    labels:
      - "traefik.enable=false"
    volumes:
      - "./docker/apache/production.conf:/etc/apache2/sites-enabled/000-default.conf"
    restart: unless-stopped

  server_web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(${HOSTS})"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=web,websecure"
    networks:
      - default
      - web
    volumes:
      - "./docker/apache/production.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro"
    restart: unless-stopped

networks:
  web:
    external:
      name: web
  default: ~
