version: '3'

services:
  php:
    build: docker/php
    tty: true
    volumes:
      - ".:/var/www/html"
      - "~/.composer:/home/docker/.composer"


  server_web:
    build: docker/apache
    volumes:
      - ".:/var/www/html"
      - "./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro"
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
    depends_on:
      - php
    links:
      - php
